import os

from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient

# We don't need to specify any credentials here, because Stratosphere will take
# care of injecting them.
CREDS = DefaultAzureCredential()

# The `azure-resource-name` is generated by the Stratosphere and will be returned
# when creating your resource. It is the same resource name as for the postgresql
# resource
client = SecretClient(vault_url="https://oxykil88mluhdd0o678krkc9.vault.azure.net", credential=CREDS)

secret_key = "administrator-login-password"
secret = client.get_secret(secret_key)


os.environ["PSQL_USERNAME"] = secret.name
os.environ["PSQL_PASSWORD"] = secret.value
